### ISSUE TITLE
Test audio markdown

### ISSUE THREAD

**Issue by Nugine** [Nugine/Amphion#1]

**Comment by SeanYouLaw** [comment]
https://github.com/Nugine/Amphion/assets/58773169/46d37ed0-00b4-4ce0-87e4-282cb2cc84da


https://github.com/Nugine/Amphion/assets/58773169/603ceef4-5d49-4850-80ab-f535250942d4


https://github.com/Nugine/Amphion/assets/58773169/bab6a0a4-0c10-46aa-a927-1e8276148d2d


https://github.com/Nugine/Amphion/assets/58773169/4574d789-262b-4c78-83df-bfeda06b12f8


https://github.com/Nugine/Amphion/assets/58773169/72e8bc90-f133-4fd7-abc9-37f4a2c86d77


https://github.com/Nugine/Amphion/assets/58773169/406e29bc-d27a-4554-878f-510b5b710b97
